Make the use of dftables optional, and not the default. Further tidies to documentation.
git-svn-id: svn://vcs.exim.org/pcre/code/trunk@128 2f5784b3-3f2a-0410-8824-cb99058d5e15

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -879,6 +879,8 @@ pcre_have_type_traits
 pcre_have_bits_type_traits
 WITH_PCRE_CPP_TRUE
 WITH_PCRE_CPP_FALSE
+WITH_REBUILD_CHARTABLES_TRUE
+WITH_REBUILD_CHARTABLES_FALSE
 pcre_have_long_long
 pcre_have_ulong_long
 EXTRA_LIBPCRE_LDFLAGS
@@ -1490,6 +1492,8 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-cpp           disable C++ support
+  --enable-rebuild-chartables
+                          rebuild character tables in current locale
   --enable-utf8           enable UTF-8 support
   --enable-unicode-properties
                           enable Unicode properties support (implies
@@ -1499,7 +1503,8 @@ Optional Features:
   --enable-newline-is-crlf
                           use CRLF as newline sequence
   --enable-newline-is-any use any valid Unicode newline sequence
-  --enable-ebcdic         assume EBCDIC coding rather than ASCII
+  --enable-ebcdic         assume EBCDIC coding rather than ASCII (implies
+                          --enable-rebuild-chartables)
   --disable-stack-for-recursion
                           don't use stack recursion when matching
 
@@ -4888,7 +4893,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4891 "configure"' > conftest.$ac_ext
+  echo '#line 4896 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7493,11 +7498,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7496: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7501: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7500: \$? = $ac_status" >&5
+   echo "$as_me:7505: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7761,11 +7766,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7764: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7769: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7768: \$? = $ac_status" >&5
+   echo "$as_me:7773: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7865,11 +7870,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7868: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7873: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7872: \$? = $ac_status" >&5
+   echo "$as_me:7877: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10210,7 +10215,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10213 "configure"
+#line 10218 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10310,7 +10315,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10313 "configure"
+#line 10318 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12646,11 +12651,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12649: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12654: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12653: \$? = $ac_status" >&5
+   echo "$as_me:12658: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12750,11 +12755,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12753: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12758: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12757: \$? = $ac_status" >&5
+   echo "$as_me:12762: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14357,11 +14362,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14360: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14365: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14364: \$? = $ac_status" >&5
+   echo "$as_me:14369: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14461,11 +14466,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14464: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14469: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14468: \$? = $ac_status" >&5
+   echo "$as_me:14473: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16696,11 +16701,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16699: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16704: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16703: \$? = $ac_status" >&5
+   echo "$as_me:16708: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16964,11 +16969,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16967: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16972: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16971: \$? = $ac_status" >&5
+   echo "$as_me:16976: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17068,11 +17073,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17071: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17076: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17075: \$? = $ac_status" >&5
+   echo "$as_me:17080: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19771,7 +19776,7 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 PCRE_MAJOR="7"
 PCRE_MINOR="1"
 PCRE_PRERELEASE="-RC2"
-PCRE_DATE="2007-03-19"
+PCRE_DATE="2007-03-20"
 
 
 
@@ -19790,6 +19795,15 @@ if test "${enable_cpp+set}" = set; then
   enableval=$enable_cpp;
 else
   enable_cpp=yes
+fi
+
+
+# Handle --enable-rebuild-chartables
+# Check whether --enable-rebuild-chartables was given.
+if test "${enable_rebuild_chartables+set}" = set; then
+  enableval=$enable_rebuild_chartables;
+else
+  enable_rebuild_chartables=no
 fi
 
 
@@ -19919,6 +19933,13 @@ fi
 if test "x$enable_utf8" = "xunset"
 then
   enable_utf8=no
+fi
+
+# Make sure that if enable_ebcdic is set, rebuild_chartables is also enabled.
+#
+if test "x$enable_ebcdie" = "xyes"
+then
+  enable_rebuild_chartables=yes
 fi
 
 # Convert the newline identifier into the appropriate integer value.
@@ -20729,6 +20750,14 @@ else
   WITH_PCRE_CPP_FALSE=
 fi
 
+ if test "x$enable_rebuild_chartables" = "xyes"; then
+  WITH_REBUILD_CHARTABLES_TRUE=
+  WITH_REBUILD_CHARTABLES_FALSE='#'
+else
+  WITH_REBUILD_CHARTABLES_TRUE='#'
+  WITH_REBUILD_CHARTABLES_FALSE=
+fi
+
 
 # Checks for typedefs, structures, and compiler characteristics.
 
@@ -21387,6 +21416,13 @@ if test -z "${WITH_PCRE_CPP_TRUE}" && test -z "${WITH_PCRE_CPP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"WITH_PCRE_CPP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WITH_PCRE_CPP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_REBUILD_CHARTABLES_TRUE}" && test -z "${WITH_REBUILD_CHARTABLES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_REBUILD_CHARTABLES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_REBUILD_CHARTABLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22084,6 +22120,8 @@ pcre_have_type_traits!$pcre_have_type_traits$ac_delim
 pcre_have_bits_type_traits!$pcre_have_bits_type_traits$ac_delim
 WITH_PCRE_CPP_TRUE!$WITH_PCRE_CPP_TRUE$ac_delim
 WITH_PCRE_CPP_FALSE!$WITH_PCRE_CPP_FALSE$ac_delim
+WITH_REBUILD_CHARTABLES_TRUE!$WITH_REBUILD_CHARTABLES_TRUE$ac_delim
+WITH_REBUILD_CHARTABLES_FALSE!$WITH_REBUILD_CHARTABLES_FALSE$ac_delim
 pcre_have_long_long!$pcre_have_long_long$ac_delim
 pcre_have_ulong_long!$pcre_have_ulong_long$ac_delim
 EXTRA_LIBPCRE_LDFLAGS!$EXTRA_LIBPCRE_LDFLAGS$ac_delim
@@ -22094,7 +22132,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 25; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -22694,6 +22732,11 @@ if test "$no_create" != yes; then
 fi
 
 
+# Make sure that pcre_chartables.c is removed in case the method for
+# creating it was changed by reconfiguration.
+
+rm -f pcre_chartables.c
+
 # Print out a nice little message after configure is run displaying your
 # chosen options.
 #
@@ -22718,6 +22761,7 @@ $PACKAGE-$VERSION configuration summary:
     Unicode properties ..... : ${enable_unicode_properties}
     Newline char/sequence .. : ${enable_newline}
     EBCDIC coding .......... : ${enable_ebcdic}
+    Rebuild char tables .... : ${enable_rebuild_chartables}
     Use stack recursion .... : ${enable_stack_for_recursion}
     POSIX mem threshold .... : ${with_posix_malloc_threshold}
     Internal link size ..... : ${with_link_size}
