Tests cleanup: use -C in RunTest; add /Z to pcretest and make test 3 independent of link size.
git-svn-id: svn://vcs.exim.org/pcre/code/trunk@116 2f5784b3-3f2a-0410-8824-cb99058d5e15

diff --git a/RunTest.in b/RunTest.in
--- a/RunTest.in
+++ b/RunTest.in
@@ -3,9 +3,6 @@
 # This file is generated by configure from RunTest.in. Make any changes
 # to that file.
 
-# TODO: Replace use of variables @LINK_SIZE@, @UTF8@ and @UCP@ with
-#       the data found from the output of 'pcretest -C' instead.
-
 # Run PCRE tests
 
 cf=diff
@@ -15,8 +12,23 @@ if [ ! -d testdata ] ; then
 fi
 testdata=./testdata
 
+# Find which optional facilities are available
 
-# Select which tests to run; if no selection, run all
+case `./pcretest -C | ./pcregrep 'Internal link size'` in
+  *2) link_size=2;;
+  *3) link_size=3;;
+  *4) link_size=4;;
+   *) echo "Failed to find internal link size"; exit 1;;
+esac
+
+./pcretest -C | ./pcregrep 'No UTF-8 support' >/dev/null
+utf8=$?
+
+./pcretest -C | ./pcregrep 'No Unicode properties support' >/dev/null
+ucp=$?
+
+# Select which tests to run; for those that are explicitly requested, check
+# that the necessary optional facilities are available.
 
 do1=no
 do2=no
@@ -45,7 +57,7 @@ while [ $# -gt 0 ] ; do
   shift
 done
 
-if [ "@LINK_SIZE@" != "2" ] ; then
+if [ "$link_size" != "2" ] ; then
   if [ $do2 = yes ] ; then
     echo "Can't run test 2 with an internal link size other than 2"
     exit 1
@@ -60,7 +72,7 @@ if [ "@LINK_SIZE@" != "2" ] ; then
   fi
 fi
 
-if [ "@UTF8@" = "no" ] ; then
+if [ $utf8 -eq 0 ] ; then
   if [ $do4 = yes ] ; then
     echo "Can't run test 4 because UTF-8 support is not configured"
     exit 1
@@ -83,7 +95,7 @@ if [ "@UTF8@" = "no" ] ; then
   fi
 fi
 
-if [ "@UCP@" = "no" ] ; then
+if [ $ucp -eq 0 ] ; then
   if [ $do6 = yes ] ; then
     echo "Can't run test 6 because Unicode property support is not configured"
     exit 1
@@ -94,18 +106,20 @@ if [ "@UCP@" = "no" ] ; then
   fi
 fi
 
+# If no specific tests were requested, select all that are relevant.
+
 if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
      $do5 = no -a $do6 = no -a $do7 = no -a $do8 = no -a \
      $do9 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
-  if [ "@UTF8@" != "no" ] ; then do4=yes; fi
-  if [ "@UTF8@" != "no" ] ; then do5=yes; fi
-  if [ "@UTF8@" != "no" -a "@UCP@" != "no" ] ; then do6=yes; fi
+  if [ $utf8 -ne 0 ] ; then do4=yes; fi
+  if [ $utf8 -ne 0 ] ; then do5=yes; fi
+  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do6=yes; fi
   do7=yes
-  if [ "@UTF8@" != "no" ] ; then do8=yes; fi
-  if [ "@UTF8@" != "no" -a "@UCP@" != "no" ] ; then do9=yes; fi
+  if [ $utf8 -ne 0 ] ; then do8=yes; fi
+  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do9=yes; fi
 fi
 
 # Show which release
@@ -129,7 +143,7 @@ fi
 # PCRE tests that are not Perl-compatible - API & error tests, mostly
 
 if [ $do2 = yes ] ; then
-  if [ "@LINK_SIZE@" = "2" ] ; then
+  if [ "$link_size" = "2" ] ; then
     echo "Test 2: API and error handling (not Perl compatible)"
     $valgrind ./pcretest -q $testdata/testinput2 testtry
     if [ $? = 0 ] ; then
@@ -140,7 +154,7 @@ if [ $do2 = yes ] ; then
     echo "OK"
     echo " "
   else
-    echo Test 2 skipped for link size other than 2 \(@LINK_SIZE@\)
+    echo Test 2 skipped for link size other than 2 \($link_size\)
     echo " "
   fi
 fi
@@ -187,7 +201,7 @@ if [ $do4 = yes ] ; then
 fi
 
 if [ $do5 = yes ] ; then
-  if [ "@LINK_SIZE@" = "2" ] ; then
+  if [ "$link_size" = "2" ] ; then
     echo "Test 5: API and internals for UTF-8 support (not Perl compatible)"
     $valgrind ./pcretest -q $testdata/testinput5 testtry
     if [ $? = 0 ] ; then
@@ -198,13 +212,13 @@ if [ $do5 = yes ] ; then
     echo "OK"
     echo " "
   else
-    echo Test 5 skipped for link size other than 2 \(@LINK_SIZE@\)
+    echo Test 5 skipped for link size other than 2 \($link_size\)
     echo " "
   fi
 fi
 
 if [ $do6 = yes ] ; then
-  if [ "@LINK_SIZE@" = "2" ] ; then
+  if [ "$link_size" = "2" ] ; then
     echo "Test 6: Unicode property support"
     $valgrind ./pcretest -q $testdata/testinput6 testtry
     if [ $? = 0 ] ; then
@@ -215,7 +229,7 @@ if [ $do6 = yes ] ; then
     echo "OK"
     echo " "
   else
-    echo Test 6 skipped for link size other than 2 \(@LINK_SIZE@\)
+    echo Test 6 skipped for link size other than 2 \($link_size\)
     echo " "
   fi
 fi
