Load pcre-6.0 into code/trunk.
git-svn-id: svn://vcs.exim.org/pcre/code/trunk@77 2f5784b3-3f2a-0410-8824-cb99058d5e15

diff --git a/RunTest.in b/RunTest.in
--- a/RunTest.in
+++ b/RunTest.in
@@ -16,6 +16,9 @@ do3=no
 do4=no
 do5=no
 do6=no
+do7=no
+do8=no
+do9=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -23,8 +26,11 @@ while [ $# -gt 0 ] ; do
     2) do2=yes;;
     3) do3=yes;;
     4) do4=yes;;
-    5) do5=yes;; 
-    6) do6=yes;; 
+    5) do5=yes;;
+    6) do6=yes;;
+    7) do7=yes;;
+    8) do8=yes;;
+    9) do9=yes;;
     *) echo "Unknown test number $1"; exit 1;;
   esac
   shift
@@ -33,48 +39,64 @@ done
 if [ "@LINK_SIZE@" != "" -a "@LINK_SIZE@" != "-DLINK_SIZE=2" ] ; then
   if [ $do2 = yes ] ; then
     echo "Can't run test 2 with an internal link size other than 2"
-    exit 1  
-  fi   
+    exit 1
+  fi
   if [ $do5 = yes ] ; then
     echo "Can't run test 5 with an internal link size other than 2"
-    exit 1  
-  fi   
+    exit 1
+  fi
   if [ $do6 = yes ] ; then
     echo "Can't run test 6 with an internal link size other than 2"
-    exit 1  
-  fi   
+    exit 1
+  fi
 fi
 
 if [ "@UTF8@" = "" ] ; then
   if [ $do4 = yes ] ; then
     echo "Can't run test 4 because UTF-8 support is not configured"
     exit 1
-  fi   
+  fi
   if [ $do5 = yes ] ; then
     echo "Can't run test 5 because UTF-8 support is not configured"
     exit 1
-  fi   
+  fi
   if [ $do6 = yes ] ; then
     echo "Can't run test 6 because UTF-8 support is not configured"
     exit 1
-  fi   
-fi    
+  fi
+  if [ $do8 = yes ] ; then
+    echo "Can't run test 8 because UTF-8 support is not configured"
+    exit 1
+  fi
+  if [ $do9 = yes ] ; then
+    echo "Can't run test 9 because UTF-8 support is not configured"
+    exit 1
+  fi
+fi
 
 if [ "@UCP@" = "" ] ; then
   if [ $do6 = yes ] ; then
     echo "Can't run test 6 because Unicode property support is not configured"
     exit 1
   fi
-fi      
+  if [ $do9 = yes ] ; then
+    echo "Can't run test 9 because Unicode property support is not configured"
+    exit 1
+  fi
+fi
 
 if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
-     $do5 = no -a $do6 = no ] ; then
+     $do5 = no -a $do6 = no -a $do7 = no -a $do8 = no -a \
+     $do9 = no ] ; then
   do1=yes
-  do2=yes 
+  do2=yes
   do3=yes
   if [ "@UTF8@" != "" ] ; then do4=yes; fi
   if [ "@UTF8@" != "" ] ; then do5=yes; fi
   if [ "@UTF8@" != "" -a "@UCP@" != "" ] ; then do6=yes; fi
+  do7=yes 
+  if [ "@UTF8@" != "" ] ; then do8=yes; fi
+  if [ "@UTF8@" != "" -a "@UCP@" != "" ] ; then do9=yes; fi
 fi
 
 # Show which release
@@ -89,15 +111,16 @@ if [ $do1 = yes ] ; then
   if [ $? = 0 ] ; then
     $cf testtry $testdata/testoutput1
     if [ $? != 0 ] ; then exit 1; fi
-    echo " " 
   else exit 1
   fi
+  echo "OK"
+  echo " "
 fi
 
 # PCRE tests that are not Perl-compatible - API & error tests, mostly
 
 if [ $do2 = yes ] ; then
-  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then   
+  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then
     echo "Test 2: API and error handling (not Perl compatible)"
     ./pcretest -i $testdata/testinput2 testtry
     if [ $? = 0 ] ; then
@@ -105,15 +128,12 @@ if [ $do2 = yes ] ; then
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
+    echo "OK"
+    echo " "
   else
-    echo Test 2 skipped for link size other than 2 \(@LINK_SIZE@\)    
-  fi   
-fi
-
-if [ $do1 = yes -a $do2 = yes ] ; then
-  echo " " 
-  echo "The two main tests ran OK"
-  echo " " 
+    echo Test 2 skipped for link size other than 2 \(@LINK_SIZE@\)
+    echo " " 
+  fi
 fi
 
 # Locale-specific tests, provided the "fr_FR" locale is available
@@ -125,21 +145,21 @@ if [ $do3 = yes ] ; then
     ./pcretest $testdata/testinput3 testtry
     if [ $? = 0 ] ; then
       $cf testtry $testdata/testoutput3
-      if [ $? != 0 ] ; then 
+      if [ $? != 0 ] ; then
         echo " "
         echo "Locale test did not run entirely successfully."
         echo "This usually means that there is a problem with the locale"
-        echo "settings rather than a bug in PCRE."    
+        echo "settings rather than a bug in PCRE."
       else
-      echo "Locale test ran OK" 
-      fi 
-      echo " " 
+      echo "OK"
+      fi
+      echo " "
     else exit 1
     fi
   else
     echo "Cannot test locale-specific features - 'fr_FR' locale not found,"
     echo "or the \"locale\" command is not available to check for it."
-    echo " " 
+    echo " "
   fi
 fi
 
@@ -147,46 +167,86 @@ fi
 
 if [ $do4 = yes ] ; then
   echo "Test 4: UTF-8 support (Perl compatible)"
-  ./pcretest $testdata/testinput4 testtry 
+  ./pcretest $testdata/testinput4 testtry
   if [ $? = 0 ] ; then
     $cf testtry $testdata/testoutput4
     if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
-  echo "UTF8 test ran OK"
+  echo "OK"
   echo " "
 fi
 
 if [ $do5 = yes ] ; then
-  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then   
+  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then
     echo "Test 5: API and internals for UTF-8 support (not Perl compatible)"
-    ./pcretest $testdata/testinput5 testtry 
+    ./pcretest $testdata/testinput5 testtry
     if [ $? = 0 ] ; then
       $cf testtry $testdata/testoutput5
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
-    echo "UTF8 internals test ran OK"
+    echo "OK"
     echo " "
   else
-    echo Test 5 skipped for link size other than 2 \(@LINK_SIZE@\)    
-  fi   
+    echo Test 5 skipped for link size other than 2 \(@LINK_SIZE@\)
+    echo " " 
+  fi
 fi
 
 if [ $do6 = yes ] ; then
-  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then   
+  if [ "@LINK_SIZE@" = "" -o "@LINK_SIZE@" = "-DLINK_SIZE=2" ] ; then
     echo "Test 6: Unicode property support"
-    ./pcretest $testdata/testinput6 testtry 
+    ./pcretest $testdata/testinput6 testtry
     if [ $? = 0 ] ; then
       $cf testtry $testdata/testoutput6
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
-    echo "Unicode properties test ran OK"
+    echo "OK"
     echo " "
-  else   
-    echo Test 6 skipped for link size other than 2 \(@LINK_SIZE@\)    
-  fi   
+  else
+    echo Test 6 skipped for link size other than 2 \(@LINK_SIZE@\)
+    echo " " 
+  fi
+fi
+
+# Tests for DFA matching support
+
+if [ $do7 = yes ] ; then
+  echo "Test 7: DFA matching"
+  ./pcretest -dfa $testdata/testinput7 testtry
+  if [ $? = 0 ] ; then
+    $cf testtry $testdata/testoutput7
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
+  fi
+  echo "OK"
+  echo " "
+fi
+
+if [ $do8 = yes ] ; then
+  echo "Test 8: DFA matching with UTF-8"
+  ./pcretest -dfa $testdata/testinput8 testtry
+  if [ $? = 0 ] ; then
+    $cf testtry $testdata/testoutput8
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
+  fi
+  echo "OK"
+  echo " "
+fi
+
+if [ $do9 = yes ] ; then
+  echo "Test 9: DFA matching with Unicode properties"
+  ./pcretest -dfa $testdata/testinput9 testtry
+  if [ $? = 0 ] ; then
+    $cf testtry $testdata/testoutput9
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
+  fi
+  echo "OK"
+  echo " "
 fi
 
 # End
