Try "french" locale if "fr_FR" not present. Update NEWS re Win32 libs.
git-svn-id: svn://vcs.exim.org/pcre/code/trunk@157 2f5784b3-3f2a-0410-8824-cb99058d5e15

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -157,17 +157,34 @@ if [ $do2 = yes ] ; then
   fi
 fi
 
-# Locale-specific tests, provided the "fr_FR" locale is available.
-# TODO: Try the locale name "french" instead - as used on Windows - but
-# this will mean modifying the input and output data.
+# Locale-specific tests, provided that either the "fr_FR" or the "french"
+# locale is available. The former is the Unix-like standard; the latter is
+# for Windows.
 
 if [ $do3 = yes ] ; then
   locale -a | grep '^fr_FR$' >/dev/null
   if [ $? -eq 0 ] ; then
-    echo "Test 3: locale-specific features (using 'fr_FR' locale)"
-    $valgrind ./pcretest -q $testdata/testinput3 testtry
+    locale=fr_FR
+    infile=$testdata/testinput3
+    outfile=$testdata/testoutput3
+  else
+    locale -a | grep '^french$' >/dev/null
+    if [ $? -eq 0 ] ; then
+      locale=french
+      sed 's/fr_FR/french/' $testdata/testinput3 >test3input
+      sed 's/fr_FR/french/' $testdata/testoutput3 >test3output
+      infile=test3input
+      outfile=test3output    
+    else
+      locale= 
+    fi
+  fi         
+
+  if [ "$locale" != "" ] ; then
+    echo "Test 3: locale-specific features (using '$locale' locale)"
+    $valgrind ./pcretest -q $infile testtry
     if [ $? = 0 ] ; then
-      $cf testtry $testdata/testoutput3
+      $cf testtry $outfile
       if [ $? != 0 ] ; then
         echo " "
         echo "Locale test did not run entirely successfully."
@@ -179,8 +196,9 @@ if [ $do3 = yes ] ; then
     else exit 1
     fi
   else
-    echo "Cannot test locale-specific features - 'fr_FR' locale not found,"
-    echo "or the \"locale\" command is not available to check for it."
+    echo "Cannot test locale-specific features - neither the 'fr_FR' nor the"
+    echo "'french' locale exists, or the \"locale\" command is not available"
+    echo "to check for them."
     echo " "
   fi
 fi
