Load pcre-2.01 into code/trunk.
git-svn-id: svn://vcs.exim.org/pcre/code/trunk@25 2f5784b3-3f2a-0410-8824-cb99058d5e15

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -9,31 +9,34 @@ cf=diff
 do1=no
 do2=no
 do3=no
+do4=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
     1) do1=yes;;
     2) do2=yes;;
     3) do3=yes;;
-    *) echo "Unknown test number $1"; exit 1;; 
+    4) do4=yes;;
+    *) echo "Unknown test number $1"; exit 1;;
   esac
   shift
 done
 
-if [ $do1 = no -a $do2 = no -a $do3 = no ] ; then
+if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
-fi     
-          
+  do4=yes
+fi
+
 # Primary test, Perl-compatible
 
 if [ $do1 = yes ] ; then
   echo "Testing main functionality (Perl compatible)"
   ./pcretest testinput testtry
-  if [ $? = 0 ] ; then 
+  if [ $? = 0 ] ; then
     $cf testtry testoutput
-    if [ $? != 0 ] ; then exit 1; fi 
+    if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
 fi
@@ -43,9 +46,9 @@ fi
 if [ $do2 = yes ] ; then
   echo "Testing API and error handling (not Perl compatible)"
   ./pcretest -i testinput2 testtry
-  if [ $? = 0 ] ; then 
-    $cf testtry testoutput2 
-    if [ $? != 0 ] ; then exit 1; fi 
+  if [ $? = 0 ] ; then
+    $cf testtry testoutput2
+    if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
 fi
@@ -55,15 +58,37 @@ fi
 if [ $do3 = yes ] ; then
   echo "Testing Perl 5.005 features (Perl 5.005 compatible)"
   ./pcretest testinput3 testtry
-  if [ $? = 0 ] ; then 
+  if [ $? = 0 ] ; then
     $cf testtry testoutput3
-    if [ $? != 0 ] ; then exit 1; fi 
+    if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
 fi
 
 if [ $do1 = yes -a $do2 = yes -a $do3 = yes ] ; then
-  echo "Tests all ran OK"
-fi   
+  echo "The three main tests all ran OK"
+  echo " " 
+fi
 
-# End    
+# Locale-specific tests, provided the "fr" locale is available
+
+if [ $do4 = yes ] ; then
+  locale -a | grep '^fr$' >/dev/null
+  if [ $? -eq 0 ] ; then
+    echo "Testing locale-specific features (using 'fr' locale)"
+    ./pcretest testinput4 testtry
+    if [ $? = 0 ] ; then
+      $cf testtry testoutput4
+      if [ $? != 0 ] ; then exit 1; fi
+      echo "Locale test ran OK" 
+      echo " " 
+    else exit 1
+    fi
+  else
+    echo "Cannot test locale-specific features - 'fr' locale not found,"
+    echo "or the \"locale\" command is not available to check for it."
+    echo " " 
+  fi
+fi
+
+# End
