Test updates.
git-svn-id: svn://vcs.exim.org/pcre/code/trunk@651 2f5784b3-3f2a-0410-8824-cb99058d5e15

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -54,6 +54,7 @@ do9=no
 do10=no
 do11=no
 do12=no
+do13=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -69,6 +70,7 @@ while [ $# -gt 0 ] ; do
    10) do10=yes;;
    11) do11=yes;;
    12) do12=yes;;
+   13) do12=yes;;
    valgrind) valgrind="valgrind -q";;
     *) echo "Unknown test number $1"; exit 1;;
   esac
@@ -88,6 +90,10 @@ if [ $utf8 -eq 0 ] ; then
     echo "Can't run test 8 because UTF-8 support is not configured"
     exit 1
   fi
+  if [ $do12 = yes ] ; then
+    echo "Can't run test 12 because UTF-8 support is not configured"
+    exit 1
+  fi
 fi
 
 if [ $ucp -eq 0 ] ; then
@@ -103,7 +109,7 @@ if [ $ucp -eq 0 ] ; then
     echo "Can't run test 10 because Unicode property support is not configured"
     exit 1
   fi
-  if [ $do12 = yes ] ; then
+  if [ $do13 = yes ] ; then
     echo "Can't run test 12 because Unicode property support is not configured"
     exit 1
   fi
@@ -132,7 +138,8 @@ if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
   if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do9=yes; fi
   if [ $link_size -eq 2 -a $ucp -ne 0 ] ; then do10=yes; fi
   do11=yes
-  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do12=yes; fi
+  if [ $utf8 -ne 0 ] ; then do12=yes; fi
+  if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do13=yes; fi
 fi
 
 # Show which release
@@ -328,10 +335,10 @@ if [ $do10 = yes ] ; then
   done   
 fi
 
-# Test of Perl >= 5.10 features
+# Test of Perl >= 5.10 features without UTF8 support
 
 if [ $do11 = yes ] ; then
-  echo "Test 11: Features from Perl >= 5.10"
+  echo "Test 11: Features from Perl >= 5.10 without UTF8 support"
   for opt in "" "-s"; do 
     $valgrind ./pcretest -q $opt $testdata/testinput11 testtry
     if [ $? = 0 ] ; then
@@ -343,14 +350,29 @@ if [ $do11 = yes ] ; then
   done   
 fi
 
-# Test non-Perl-compatible Unicode property support
+# Test of Perl >= 5.10 features with UTF8 support
 
 if [ $do12 = yes ] ; then
-  echo "Test 12: API, internals, and non-Perl stuff for Unicode property support"
+  echo "Test 12: Features from Perl >= 5.10 with UTF8 support"
   for opt in "" "-s"; do 
     $valgrind ./pcretest -q $opt $testdata/testinput12 testtry
     if [ $? = 0 ] ; then
       $cf $testdata/testoutput12 testtry
+      if [ $? != 0 ] ; then exit 1; fi
+    else exit 1
+    fi
+    if [ "$opt" = "-s" ] ; then echo "OK with study" ; else echo "OK"; fi
+  done   
+fi
+
+# Test non-Perl-compatible Unicode property support
+
+if [ $do13 = yes ] ; then
+  echo "Test 13: API, internals, and non-Perl stuff for Unicode property support"
+  for opt in "" "-s"; do 
+    $valgrind ./pcretest -q $opt $testdata/testinput13 testtry
+    if [ $? = 0 ] ; then
+      $cf $testdata/testoutput13 testtry
       if [ $? != 0 ] ; then exit 1; fi
     else exit 1
     fi
